###Changed by KP
version: '3'
services:
  ecsdemo-nodejs:
    image: brentley/ecsdemo-nodejs
    ports:
      - "3000:3000"
    logging:
      driver: awslogs
      options: 
        awslogs-group: ecsdemo-nodejs
        awslogs-region: ap-southeast-2
        awslogs-stream-prefix: ecsdemo-nodejs
